version: '3.8'

services:
  postgres:
    image: postgres:14.2
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${smartphone-shop}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - bp-network
    env_file:
      - .env

  backend:
    restart: always
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: './backend'
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./backend:/svr/app
      - /svr/app/node_modules
    ports:
      - '${PORT}:3003'
    env_file: .env
    networks:
      - bp-network

  frontend:
    restart: always
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: "./frontend"
    depends_on:
      - backend # todo: might not be necessary
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    ports:
      - "5173:5173"
    env_file: .env
    networks:
      - bp-network

  pgadmin-portal:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin-portal
    env_file:
      - ./backend/.env
    environment:
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5055:80"
    depends_on:
      - postgres
    networks:
      - bp-network

volumes:
  pg_data:
  pgadmin:

networks:
  bp-network:
    driver: bridge